version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9009:9009"
    env_file:
      - .env
    depends_on:
      - mongo
  mongo:
    image: mongo:5.0.14
    ports:
      - "27017:27017"
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

